'''
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def even_sum(limit):
    fib_even = []
    a,b = 1,1
    while b <= limit:
        fib_even.append(a+b)
        a,b = a+(2*b),(2*a)+(3*b)
    return fib_even
  
 
limit = 4000000
print(even_sum(limit))
